export const menu = [
  {
    id: 1,
    name: "Thai Prawn Crackers",
    price: 3.25,
    preview: "/assets/images/papayaya/PrawnCrackers.jpg",
    category: "starters",
    allergy: "Crustaceans",
    description: `Spicy crackers served with sweet chilli dipping sauce.`,
  },
  {
    id: 2,
    name: "Japanese Edamame",
    price: "5.50",
    // preview: "/assets/images/papayaya/Papayaya_JapaneseEdamame.jpg",
    category: "starters",
    allergy: "Soya",
    description: `With light sea salt flakes.`,
  },
  {
    id: 3,
    name: "Chicken Satay",
    price: "6.95",
    preview: "/assets/images/papayaya/ChickenSatay.jpg",
    category: "starters",
    allergy: "Peanuts",
    description: `Succulent chicken skewers served with peanut dipping sauce.`,
  },
  {
    id: 4,
    name: "Crispy Spicy Thai Chicken Wings",
    price: "6.95",
    preview: "/assets/images/papayaya/ChickenWings.jpg",
    category: "starters",
    allergy: "Gluten, Soya",
    description: `Deep fried wings, wok tossed with Thai chilli and peppercorn salt.`,
  },
  {
    id: 5,
    name: "Crispy Fried Wanton (NEW)",
    price: "6.95",
    // preview: "/assets/images/menu/tuscan-grilled.jpg",
    category: "starters",
    allergy: "Crustaceans, Gluten, Egg",
    description: `Wrapped with minced prawns and pork served with sweet chilli dipping sauce.`,
  },
  {
    id: 6,
    name: "Tender Meaty Spare Ribs - spicy",
    price: "7.50",
    preview: "/assets/images/papayaya/BBQRibs.jpg",
    category: "starters",
    allergy: "Soya, Sesame Seeds, Gluten",
    description: `Marinated in spicy Korean BBQ sauce topped with sesame seeds.`,
  },
  {
    id: 7,
    name: "Tender Meaty Honey Spare Ribs (NEW)",
    price: "7.50",
    // preview: "/assets/images/menu/greek-salad.jpg",
    category: "starters",
    allergy: "Soya, Sesame Seeds, Gluten",
    description: `Glazed in honey sauce topped with sesame seeds.`,
  },
  {
    id: 8,
    name: "Thai Fish Cakes",
    price: "6.95",
    // preview: "/assets/images/menu/spinach-salad.jpg",
    category: "starters",
    allergy: "Fish, Gluten",
    description: `Fish cakes flavoured with red curry paste, fine beans and lime leaves served with sweet chilli dipping sauce.`,
  },
  {
    id: 9,
    name: "Crispy Vegetable Spring Rolls",
    price: "6.50",
    preview: "/assets/images/papayaya/VegSpringRoll.jpg",
    category: "starters",
    allergy: "Vegetarian, Soya, Gluten",
    description: `Vermicelli noodles, shredded fungus and mixed vegetables wrapped in pastry. Served with sweet chilli dipping sauce.`,
  },
  {
    id: 10,
    name: "Crispy Aromatic Duck Spring Rolls",
    price: "7.50",
    preview: "/assets/images/papayaya/DuckRoll.jpg",
    category: "starters",
    allergy: "Soya, Gluten",
    description: `Aromatic duck wrapped in pastry, served with hoisin dipping sauce.`,
  },
  {
    id: 11,
    name: "Cripsy Sesame Prawn Rolls",
    price: "6.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Crustaceans, Gluten, Sesame Seeds, Soya",
    description: `Minced prawns wrapped in pastry, sesame seed coating served with sweet
      chilli dipping sauce.`,
  },
  {
    id: 12,
    name: "Thai Spicy Corn Fritters",
    price: "6.50",
    preview: "/assets/images/papayaya/CornFritters.jpg",
    category: "starters",
    allergy: "Vegetarian, Gluten",
    description: `Sweetcorn mixed with mild curry paste, deep fried and served with sweet chilli sauce.`,
  },
  {
    id: 13,
    name: "Battered Vegetable (NEW)",
    price: "5.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Vegetarian, Soya, Gluten",
    description: `Crispy battered vegetables served with sweet chilli dipping sauce.`,
  },
  {
    id: 14,
    name: "Butterfly Prawn",
    price: "7.50",
    preview: "/assets/images/papayaya/ButterflyPr.jpg",
    category: "starters",
    allergy: "Crustaceans, Gluten, Soya, Egg",
    description: `Crispy battered prawns with sweet chilli dipping sauce.`,
  },
  {
    id: 15,
    name: "Popcorn Shrimp",
    price: "6.95",
    preview: "/assets/images/papayaya/PopcornShrimp.jpg",
    category: "starters",
    allergy: "Crustaceans, Gluten, Soya, Sesame Seeds",
    description: `Served with wasabi mayonaise, topped with black sesame seeds.`,
  },
  {
    id: 16,
    name: "Gyoza - Vegetable dumplings",
    price: 5.95,
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Vegetarian, Soya, Gluten",
    description: `Pan fried vegetable dumplings served with japanese soy sauce.`,
  },
  {
    id: 17,
    name: "Gyoza- Chicken dumplings",
    price: "6.50",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Soya, Gluten",
    description: `Pan fried chicken dumplings served with japanese soy sauce.`,
  },
  {
    id: 18,
    name: "Tom Yum Soup",
    preview: "/assets/images/papayaya/TomYumSoup.jpg",
    price: "-", // price varies
    category: "starters",
    allergy: "Fish, Crustaceans, Milk",
    options: [
      { name: "Chicken", price: "6.50" },
      { name: "Prawn", price: "6.95" },
      { name: "Oyster mushroom", price: "5.95" },
    ],
    description: `Popular Thai spicy and sour soup with mushroom, lemongrass, galangal, coriander, chilli, lemon juice and fish sauce.`,
  },
  {
    id: 19,
    name: "Tom Kha Soup",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    price: "-", // price varies
    category: "starters",
    allergy: "Crustaceans, Fish",
    options: [
      { name: "Chicken", price: "6.50" },
      { name: "Prawn", price: "6.95" },
      { name: "Oyster mushroom", price: "5.95" },
    ],
    description: `Popular Thai creamy spicy soup cooked with coconut milk, galangal, lemongrass, lime leaves, chilli, coriander, lemon juice and fish sauce.`,
  },
  {
    id: 20,
    name: "Som Tum (Thai Papaya Salad)",
    price: "8.50",
    preview: "/assets/images/papayaya/SomTum.jpg",
    category: "starters",
    allergy: "Peanut, Fish, Crustaceans",
    description: `Shredded Thai green papaya pounded with cherry tomato, dried shrimp, chilli, peanut, palm sugar, fish sauce and lemon juice dressing.`,
  },
  {
    id: 21,
    name: "Thai Fried Tofu",
    price: 5.95,
    preview: "/assets/images/papayaya/FriedTofu.jpg",
    category: "starters",
    allergy: "Peanut, Soya, Vegetarian",
    description: `Crispy Tofu served with ground peanut and sweet chilli dipping sauce.`,
  },
  {
    id: 22,
    name: "Roti (flat bread) with Curry Sauce",
    price: "6.50",
    preview: "/assets/images/papayaya/RotiCanai.jpg",
    category: "starters",
    allergy: "Gluten, Vegetarian, Soya",
    description: `Crispy pan fried roti served with curry sauce.`,
  },
  {
    id: 23,
    name: "Salt and Pepper Crispy Squid OR Prawn",
    price: "7.50",
    preview: "/assets/images/papayaya/S&PSquid.jpg",
    category: "starters",
    allergy: "Egg, Crustaceans, Molluscs, Gluten",
    description: `Deep fried and wok tossed with Thai chilli and peppercorn salt.`,
  },
  {
    id: 24,
    name: "Soft Shell Crab",
    price: 8.25,
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Crustaceans, Gluten, Egg",
    description: `Deep fried crispy soft shell crab served with sweet chilli dipping sauce.`,
  },

  {
    id: 25,
    name: "Selection of Aromatic Duck Roll, Gyoza Chicken, Butterfly Prawn, Chicken Satay withe peanut sauce, Vegetable Spring Roll",
    price: "16.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Peanut, Soya, Gluten, Crustanceans, Egg, Sesame",
    description: `2 of each item.`,
  },
  {
    id: 26,
    name: "Selection of Edamame, Vegetable Spring Roll, Thai Corn Cake fritter, Gyoza Vegetable and Fried Tofu with peanut",
    price: 14.95,
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "starters",
    allergy: "Peanut, Vegetarian, Soya, Gluten, Sesame",
    description: `2 of each item.`,
  },

  //   // Soup noodles
  {
    id: 27,
    name: "Malaysian Curry Laksa Soup",
    price: "12.95",
    preview: "/assets/images/papayaya/CurryLaksa.jpg",
    category: "soup-noodles",
    allergy: "Crustaceans, Molluscs, Fish, Soya, Gluten, Celery, Egg, Nut",
    description: `Prawn, squid, fish ball, fish roll, chicken, fine bean, bean sprout and fried tofu in curry soup made from coconut milk herbs and mixed spices. Choice of egg noodle OR rice vermicelli noodle.`,
  },
  {
    id: 28,
    name: "Thai Sukiyaki Soup Noodle",
    price: "12.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "soup-noodles",
    allergy: "Soya, Fish, Molluscs, Crustaceans, Sesame",
    description:
      "Prawns, squids, fish ball, fish roll, Chinese leaves kangkung and clear vermicelli noodles.",
  },
  {
    id: 29,
    name: "Wanton Noodle Soup (NEW)",
    price: "11.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "soup-noodles",
    allergy: "Egg, Crustaceans, Gluten",
    description: `Egg noodles, green bok choi and wanton served with clear soup.`,
  },
  {
    id: 30,
    name: "Vietnamese Pho",
    price: "-",
    preview: "/assets/images/papayaya/VietnamesePhoCh.jpg",
    category: "soup-noodles",
    allergy: "Crustaceans, Fish, Soy",
    options: [
      { name: "Beef", price: "11.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],

    description: `Famous Vietnamese clear soup served with fresh bean sprout, sweet basil sliced chilli, lemon and ho fun (rice noodle).`,
  },
  {
    id: 31,
    name: "Tom Yum Noodle Soup (NEW)",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "soup-noodles",
    allergy: "Crustaceans, Fish, Milk",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],

    description: `Popular Thai Spicy and sour soup with mushroom, lemongrass, galangal, coriander, roast chilli and rice vermicelli noodle.`,
  },
  {
    id: 32,
    name: "Ramen Miso",
    price: 10.95,
    // preview: "/assets/images/papayaya/RamenMiso.jpg",
    category: "soup-noodles",
    allergy: "Soya, Gluten, Vegetarian, Sesame",
    description: `Ramen noodles in a homemade miso paste soup, with seaweed, carrots, bamboo shoots, courgette and tofu.`,
  },

  // Noodles and Rice
  {
    id: 33,
    name: "Pad Thai",
    price: "-",
    preview: "/assets/images/papayaya/PadThai.jpg",
    category: "noodles-rice",
    allergy: "Peanut, Egg, Fish, Crustaceans",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Popular Thai wok fried noodles, egg, bean curd, bean sprouts, chive, sweet turnip, peanut, chilli flakes, lemon with a homemade sauce.`,
  },
  {
    id: 34,
    name: "Char Kwei Tiew",
    price: "-",
    preview: "/assets/images/papayaya/CharKweiTeow.jpg",
    category: "noodles-rice",
    allergy: "Soy, Crustaceans, Egg",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Beef", price: "11.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Popular Malaysian wok fried fresh hofun, egg, bean sprout, chives, spring onion with dark sweet soy sauce.`,
  },
  {
    id: 35,
    name: "Singapore Fried Noodle",
    price: "-",
    preview: "/assets/images/papayaya/Singapore_noodle.jpeg",
    category: "noodles-rice",
    allergy: "Egg, Soy, Crustaceans, Sesame",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried rice vermicelli noodles, egg, bean sprout, onion with curry spices.`,
  },
  {
    id: 36,
    name: "Mee Goreng",
    price: "-", // price varies
    preview: "/assets/images/papayaya/MeeGorengPr.jpg",
    category: "noodles-rice",
    allergy: "Egg, Gluten, Crustaceans, Soy, Sesame Seed",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried noodles with eggs, bok choi, beansprout, onions and tofu.`,
  },
  {
    id: 37,
    name: "Yaki Soba",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "noodles-rice",
    allergy: "Egg, Soy, Gluten, Crustaceans, Sesame Seed",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried Japanese noodles with cabbage, carrot, spring onion, bean sprout and mixed peppers.`,
  },
  {
    id: 38,
    name: "Pad Kimao - spicy Thai noodle",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "noodles-rice",
    allergy: "Soy, Fish, Crustaceans",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried fresh Hofun noodles with minced Thai chilli and Thai basil.`,
  },
  {
    id: 39,
    name: "Japanese Udon Noodle in sambal sauce (NEW)",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "noodles-rice",
    allergy: "Crustaceans, Soy, Gluten",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Beef", price: "11.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried Udon noodles in sambal sauce.`,
  },
  {
    id: 40,
    name: "Hofun with Black bean sauce (NEW)",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "noodles-rice",
    allergy: "Crustaceans, Soy, Sesame",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Beef", price: "11.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried ho fun noodles with black bean sauce - mild.`,
  },
  {
    id: 41,
    name: "Papayaya Fried Rice",
    price: "-",
    preview: "/assets/images/papayaya/PapayayaFriedRice.jpg",
    category: "noodles-rice",
    allergy: "Soy, Crustaceans, Egg",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Beef", price: "11.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried rice with green curry paste, sweet basil, thai aubergine, egg and lime leaves.`,
  },
  {
    id: 42,
    name: "Nasi Goreng with sambal sauce",
    price: "-",
    preview: "/assets/images/papayaya/NasiGorengPr.jpg",
    category: "noodles-rice",
    allergy: "Egg, Crustaceans, Soy",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Beef", price: "11.95" },
      { name: "Chicken", price: "11.50" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried rice with sambal sauce, onions, carrot, egg and mixed peppers.`,
  },
  {
    id: 43,
    name: "Hokkien Mee - Malaysian classic",
    price: "12.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "noodles-rice",
    allergy: "Soy, Molluscs, Crustaceans, Gluten, Egg",
    description: `Wok fried egg noodles with prawns, squid, pork, bok choi and dark caramel sauce.`,
  },
  {
    id: 44,
    name: "Chicken Teriyaki",
    price: "11.50",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "noodles-rice",
    allergy: "Soy, Gluten",
    description: `Tender breaded chicken marinated in teriyaki sauce with bean sprout. Served with Jasmine Rice.`,
  },

  // Wok fry dishes
  {
    id: 56,
    name: "Sambal Prawns OR Beef",
    price: "12.50",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "wok-fry",
    allergy: "Crustaceans, Soy",
    description: `Wok fried prawns OR beef with onions, cherry tomatoes, mixed peppers in sambal chilli paste. Served with Jasmine Rice.`,
  },
  {
    id: 57,
    name: "Prawn Kangkung with Sambal Chilli Paste (spicy)",
    price: "12.50",
    preview: "/assets/images/papayaya/PrawnKangKung.jpg",
    category: "wok-fry",
    allergy: "Crustaceans, Soy",
    description: `Wok fried prawns with kangkung and sambal chilli paste. Served with Jasmine Rice.`,
  },
  {
    id: 58,
    name: "Thai Beef with Oyster sauce",
    price: "11.95",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "wok-fry",
    allergy: "Molluscs, Gluten, Soy, Sesame",
    description: `Wok fried beef with minced chilli, fine beans, onion, garlic and basil. Served with Jasmine Rice.`,
  },
  {
    id: 59,
    name: "Roast Duck with Thai tamarind sauce",
    price: "12.50",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "wok-fry",
    allergy: "Fish, Gluten, Soy",
    description: `Roast duck breast infused in Thai tamarind sauce. Served with Jasmine Rice.`,
  },
  {
    id: 60,
    name: "King Prawn with Thai tamarind sauce (NEW)",
    price: "12.50",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "wok-fry",
    allergy: "Crustaceans, Fish, Gluten, Soy",
    description: `King prawn infused in Thai tamarind sauce. Served with Jasmine Rice.`,
  },
  {
    id: 61,
    name: "Stir Fried Cashew Nuts",
    price: "-",
    preview: "/assets/images/papayaya/CashewNutsCh.jpg",
    category: "wok-fry",
    allergy: "Nut, Soy, Crustaceans, Molluscs, Sesame",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken,", price: "11.50" },
      { name: "Beef", price: "11.95" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Stir fried cashew nuts with bamboo shoot, mushroom, onions and carrots. Served with Jasmine Rice.`,
  },
  {
    id: 62,
    name: "Pad Krapao",
    price: "-",
    preview: "/assets/images/papayaya/PadKrapao.jpg",
    category: "wok-fry",
    allergy: "Gluten, Crustaceans, Fish, Molluscs",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken,", price: "11.50" },
      { name: "Beef", price: "11.95" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Classic Thai dish stir fried with minced chilli, garlic and hot basil. Served with Jasmine Rice.`,
  },
  {
    id: 63,
    name: "Stir Fried ginger, garlic and spring onion",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "wok-fry",
    allergy: "Soy, Gluten, Crustaceans, Mollusc",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken,", price: "11.50" },
      { name: "Beef", price: "11.95" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried ginger, garlic, spring onion and mixed peppers with oyster sauce. Served with Jasmine Rice.`,
  },
  {
    id: 64,
    name: "Thai Sweet and Sour sauce",
    price: "-",
    preview: "/assets/images/papayaya/SweetNsourCH.jpg",
    category: "wok-fry",
    allergy: "Celery, Sulphur Dioxide, Gluten, Crustaceans",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken,", price: "11.50" },
      { name: "Beef", price: "11.95" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried mixed peppers, onion, pineapple and cherry tomatoes in sweet and sour sauce. Served with Jasmine Rice.`,
  },
  {
    id: 65,
    name: "Wok fried black bean sauce",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "wok-fry",
    allergy: "Crustaceans, Soy, Sesame",
    options: [
      { name: "Vegetable", price: "10.95" },
      { name: "Chicken,", price: "11.50" },
      { name: "Beef", price: "11.95" },
      { name: "Prawn", price: "12.50" },
    ],
    description: `Wok fried mixed pepper, onion, ginger, garlic, chilli with black bean sauce. Served with Jasmine Rice. `,
  },

  // kids menu
  {
    id: "K1",
    name: "Gyoza Vegetable",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "kids",
    allergy: "Soy, Gluten, Vegetarian",
    description:
      "Choose a starter, a main plus 1 scoop of Vanilla Ice-cream for £9.50",
  },
  {
    id: "K2",
    name: "Crispy Vegetable Spring Rolls",
    price: "-",
    preview: "/assets/images/papayaya/VegSpringRoll.jpg",
    category: "kids",
    allergy: "Soy, Gluten, Vegetarian",
    description:
      "Choose a starter, a main plus 1 scoop of Vanilla Ice-cream for £9.50",
  },
  {
    id: "K3",
    name: "Wok fried noodles with egg and chicken",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "kids",
    allergy: "Egg, Gluten, Soy",
    description:
      "Choose a starter, a main plus 1 scoop of vanilla Ice-cream for £9.50",
  },
  {
    id: "K4",
    name: "Wok fried rice with eggs, sweetcorn and chicken",
    price: "-",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "kids",
    allergy: "Egg, Soy",
    description:
      "Choose a starter, a main plus 1 scoop of vanilla Ice-cream for £9.50",
  },

  {
    id: "K5",
    name: "Vanilla Ice Cream",
    price: "-",
    preview: "/assets/images/papayaya/ThaiIceCream.jpg",
    category: "kids",
    allergy: "Milk",
    description:
      "Choose a starter, a main plus 1 scoop of vanilla Ice-cream for £9.50",
  },

// additional topping
  {
    id: "SM1",
    name: "Katsu Sauce",
    price: "2.00",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "Additional-Topping",
    allergy: "Gluten, Soy, Celery",
  },
  {
    id: "SM2",
    name: "Vegetable Curry Sauce",
    price: "2.00",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "Additional-Topping",
    allergy: "Soy, Nut, Mustard",
  },
  {
    id: "SM3",
    name: "Sambal Sauce",
    price: "1.00",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "Additional-Topping",
    allergy: "Crustacean, Soy",
  },
  {
    id: "SM4",
    name: "Satay Sauce",
    price: "1.00",
    // preview: "/assets/images/menu/lobster-roll.jpg",
    category: "Additional-Topping",
    allergy: "Peanut",
  },
];
